---
- name: install caddy
  become: yes
  unarchive:
    src: https://github.com/caddyserver/caddy/releases/download/v2.3.0/caddy_2.3.0_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags:
    - caddy
