---
- name: install shfmt
  become: yes
  get_url:
    url: https://github.com/mvdan/sh/releases/download/v3.2.1/shfmt_v3.2.1_linux_amd64
    dest: /usr/local/bin/shfmt
    force: yes
    mode: 0755
  tags:
    - shfmt
