---
- name: install direnv
  become: yes
  get_url:
    url: https://github.com/direnv/direnv/releases/download/v2.21.3/direnv.linux-amd64
    dest: /usr/local/bin/direnv
    mode: 0755
  tags:
    - direnv
