---
- name: copy bashrc
  become: yes
  copy:
    src: ../files/.bashrc
    dest: "{{ ansible_user_dir }}"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - bashrc