---
- name: install exa
  become: yes
  unarchive:
    src: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    dest: /usr/local/bin
    remote_src: yes

- name: rename exa
  become: yes
  shell: "mv /usr/local/bin/exa-linux-x86_64 /usr/local/bin/exa"
  changed_when: false
