---
- name: install sysstat
  become: yes
  apt:
    state: present
    name: sysstat

- name: edit sysstat file
  become: yes
  shell: 'echo ENABLED="true" > /etc/default/sysstat'
  changed_when: false

- name: start sysstat
  become: yes
  systemd:
    name: sysstat
    enabled: yes
    state: started
