---
- name: download go
  become: yes
  get_url:
    url: https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
    dest: /var/tmp/go.linux-amd64.tar.gz

- name: unarchive go.tar.gz
  become: yes
  unarchive:
    src: /var/tmp/go.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
