- name: download go
  get_url:
    url: https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
    dest: /var/tmp/go1.13.7.linux-amd64.tar.gz

- name: unarchive go.tar.gz
  unarchive:
    src: /var/tmp/go1.13.7.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
