---
- name: install goss
  become: yes
  get_url:
    url: https://github.com/aelsabbahy/goss/releases/download/v0.3.16/goss-linux-amd64
    dest: /usr/local/bin/goss
    force: yes
    mode: 0755
  tags:
    - goss
