- name: apt install packages for pyenv
  apt:
    name:
      - build-essential
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev

- name: clone pyenv
  shell: |
    if [ ! -d /home/vagrant/.pyenv ]; then 
      git clone https://github.com/pyenv/pyenv.git /home/vagrant/.pyenv
    else 
      echo SKIP
    fi

    chown -R vagrant:vagrant /home/vagrant/.pyenv

  changed_when: false

- name: copy .pyenvrc
  copy:
    src: ../files/.pyenvrc
    dest: /home/vagrant
    mode: 0644
    owner: vagrant
    group: vagrant
