---
- name: apt install packages
  become: yes
  apt:
    state: present
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: "3600"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: apt-key add
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: set stable docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: "3600"

- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups:
      - docker

- name: start docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: download docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
