- name: apt install packages
  apt:
    state: latest
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: apt-key add
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: set edge docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
    state: present
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: latest

- name: edit groups of {{ user }}
  user:
    name: "{{ user }}"
    groups: vagrant,docker

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
