---
- name: apt install packages
  become: yes
  apt:
    state: present
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: "3600"
  vars:
    packages:
      - wget
      - sudo
      - tar
      - zip
      - unzip
      - unzip
      - bzip2
      - tree
      - git
      - vim
      - jq
      - awscli
      - zstd
      - python3-pip
      - xsel
      - shellcheck
      - stress
      - ansible
      - build-essential

- name: install goss
  become: yes
  get_url:
    url: https://github.com/aelsabbahy/goss/releases/download/v0.3.11/goss-linux-amd64
    dest: /usr/local/bin/goss
    mode: 0755
