---
- name: apt install packages
  become: yes
  apt:
    state: present
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: "3600"
  vars:
    packages:
      - wget
      - sudo
      - tar
      - zip
      - unzip
      - unzip
      - bzip2
      - tree
      - git
      - vim
      - jq
      - awscli
      - zstd
      - python3-pip
      - xsel
      - shellcheck
      - stress
      - ansible
      - build-essential

- name: copy bashrc
  become: yes
  copy:
    src: ../files/.bashrc
    dest: "{{ ansible_user_dir }}"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
