- name: apt update
  apt:
    update_cache: yes
- name: apt install packages
  apt:
    state: latest
    name:
      - wget
      - sudo
      - tar
      - zip
      - unzip
      - unzip
      - bzip2
      - tree
      - git
      - vim
      - jq
      - awscli
      - zstd

- name: copy vim setting file
  copy:
    src: ../files/vim/.vimrc
    dest: "{{ home_dir }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"

- name: install neobundle
  shell: |
    curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh > /var/tmp/install.sh
    sh /var/tmp/install.sh

- name: copy bashrc
  copy:
    src: ../files/bashrc/.bashrc
    dest: "{{ home_dir }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
