---
- name: apt install packages
  become: yes
  apt:
    state: present
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: "3600"
  vars:
    packages:
      - wget
      - tar
      - zip
      - unzip
      - unzip
      - bzip2
      - tree
      - git
      - vim
      - jq
      - awscli
      - zstd
      - xsel
      - shellcheck
      - stress
      - ansible
      - htop
