- name: apt update
  apt:
    update_cache: yes
- name: apt install packages
  apt:
    state: latest
    name:
      - wget
      - sudo
      - tar
      - zip
      - unzip
      - unzip
      - bzip2
      - tree
      - git
      - vim
      - jq
      - awscli
      - zstd

- name: copy vim setting file
  copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - ../files/vim/.vimrc
    - ../files/vim/.gvimrc

- name: copy bashrc
  copy:
    src: ../files/bashrc/.bashrc
    dest: "{{ home_dir }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
